# Generated by Django 3.2.7 on 2021-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchman',
            name='profile_pic',
            field=models.FileField(default='media/defaultm.png', upload_to='media/images'),
        ),
    ]
