# Generated by Django 3.2.7 on 2021-09-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchman', '0002_alter_watchman_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
