# Generated by Django 3.2.7 on 2021-09-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watchman', '0003_watchman_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchman',
            name='is_rejected',
        ),
    ]
