# Generated by Django 3.2.7 on 2021-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchman', '0004_remove_watchman_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
