# Generated by Django 3.2.7 on 2021-09-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman', '0003_chairman'),
        ('Watchman', '0005_watchman_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileno', models.CharField(max_length=30)),
                ('reason', models.CharField(default='Casual', max_length=200)),
                ('visited_on', models.DateTimeField(auto_now_add=True)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.house')),
            ],
        ),
    ]
