# Generated by Django 3.2.7 on 2021-09-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chairman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=30)),
                ('job_specification', models.CharField(max_length=50)),
                ('job_address', models.TextField(max_length=500)),
                ('birthdate', models.CharField(max_length=20)),
                ('no_of_members', models.CharField(max_length=30)),
                ('marrital_status', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('no_of_vehicles', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('id_proof', models.FileField(default='media/default.png', upload_to='media/documents')),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.user')),
            ],
        ),
    ]
