# Generated by Django 3.2.7 on 2021-09-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman', '0003_chairman'),
        ('MemberApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=30)),
                ('job_specification', models.CharField(max_length=50)),
                ('job_address', models.TextField(max_length=500)),
                ('birthdate', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('relation', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.user')),
            ],
        ),
    ]
