# Generated by Django 3.2.7 on 2021-09-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0002_family_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_member',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member'),
        ),
    ]
