# Generated by Django 3.2.7 on 2021-09-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0003_alter_family_member_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=1000)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('video', models.FileField(null=True, upload_to='media/videos/', verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
