# Generated by Django 3.2.7 on 2021-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0006_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.FileField(default='media/events.png', upload_to='media/images/'),
        ),
    ]
