# Generated by Django 3.2.7 on 2021-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0007_alter_event_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pic',
            field=models.FileField(default='media/notice.png', upload_to='media/images/'),
        ),
    ]
