# Generated by Django 3.2.7 on 2021-09-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0009_complain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
