# Generated by Django 3.2.7 on 2021-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0011_complain_event_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='video',
            field=models.FileField(null=True, upload_to='media/videos/', verbose_name='video'),
        ),
    ]
