# Generated by Django 3.2.7 on 2021-09-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0012_alter_notice_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Complain',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
