# Generated by Django 3.2.7 on 2021-09-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0015_remove_family_member_member_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
